### ISSUE TITLE
[BUG] Rift Explorer fails to start with `ERR_PACKAGE_PATH_NOT_EXPORTED`

### ISSUE THREAD

**Issue by bayu01** [Pupix/rift-explorer#168]
**Bug Description**  
Rift Explorer fails to start

**Problem Description**  
After running `yarn dev` it crashes with the following stack:

```
yarn run v1.22.19
$ tsc -p app && concurrently "cross-env BROWSER=none NODE_ENV=development yarn react:start" "wait-on http://localhost:3000/ && electron ./build/app/entry.js"
$ rescripts start
[0] node:internal/modules/cjs/loader:544
[0]       throw e;
[0]       ^
[0] 
[0] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/pedrojacques/workspace/rift-explorer/node_modules/postcss-safe-parser/node_modules/postcss/package.json
[0]     at new NodeError (node:internal/errors:400:5)
[0]     at exportsNotFound (node:internal/modules/esm/resolve:361:10)
[0]     at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
[0]     at resolveExports (node:internal/modules/cjs/loader:538:36)
[0]     at Module._findPath (node:internal/modules/cjs/loader:607:31)
[0]     at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
[0]     at Module._load (node:internal/modules/cjs/loader:885:27)
[0]     at Module.require (node:internal/modules/cjs/loader:1105:19)
[0]     at require (node:internal/modules/cjs/helpers:103:18)
[0]     at Object.<anonymous> (/Users/pedrojacques/workspace/rift-explorer/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
[0]   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
[0] }
[0] 
[0] Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] cross-env BROWSER=none NODE_ENV=development yarn react:start exited with code 1
```

**Repro Steps**  

System settings
Mac OS Ventura 13.1 (22C65) Apple's M1 chip
Node v18.13.0
Yarn 1.22.19
League Client (for Mac) v13.1

1. Checkout Rift-Explorer [v6.3.0](https://github.com/Pupix/rift-explorer/releases/tag/V6.3.0) 
2. yarn install
3. Start League Client
4. yarn dev

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful.

**Comment by d4sein** [comment]
I'm having the same issue running yarn build on a Win 10.
```
yarn run v1.22.19
$ yarn && tsc -p app && rescripts build && yarn electron-pack
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in D:\Documents\rift-explorer\node_modules\postcss-safe-parser\node_modules\postcss\package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\Documents\rift-explorer\node_modules\postcss-safe-parser\lib\safe-parser.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.12.1
```

**Comment by d4sein** [comment]
Downloading the source code from release fixed it for me, but the app is unable to launch the client now..

**Comment by QuantumKuba** [comment]
> Downloading the source code from release fixed it for me, but the app is unable to launch the client now..

Yup I'm having the same issue

**Comment by d4sein** [comment]
> Yup I'm having the same issue

Just realized the app is no longer under maintenance, on the README it recommends using one called LCU Explorer, this one works for me (with performance issues, but works).

Try it out.

**Comment by tomek7667** [comment]
It would be very useful for the author to include node version in readme.md as it seems to be the problem.
