### ISSUE TITLE
32bit built doesn't work

### ISSUE THREAD

**Issue by GGPeridot** [Pupix/rift-explorer#88]
recently, I just built a 32bit version which I followed what the readme.md told me to do. And it doesn't work it always show "Waiting for League to start" I also got this message after running "npm start"
 Error: Could not connect
    at Socket.onerror (G:\rift32bit\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (events.js:288:20)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by RayZz-** [comment]
Comment out https://github.com/Pupix/rift-explorer/blob/af3ca543b3366a21c3cfe6c2e158e319b4becb71/app.js#L142

like this: `// rpc.login({ clientId }).catch(console.error);`

and see if the issue persists

**Comment by GGPeridot** [comment]
what do you mean by that?

**Comment by RayZz-** [comment]
Change the line from the original line to the second one shown and rebuild and see if the issue still happens

**Comment by GGPeridot** [comment]
I will try and see then

**Comment by GGPeridot** [comment]
nope, the issues is even more worse after doing that it didnt even load and it said:
G:\The ParadoxBoxTrox\Tools and Misc\RiftExplorer32BitBuildByGabonnie>npm start

> rift-explorer@6.2.0 start G:\The ParadoxBoxTrox\Tools and Misc\RiftExplorer32B
itBuildByGabonnie
> electron app


 App threw an error during load
G:\The ParadoxBoxTrox\Tools and Misc\RiftExplorer32BitBuildByGabonnie\app.js:149




SyntaxError: Unexpected end of input
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at loadApplicationPackage (G:\The ParadoxBoxTrox\Tools and Misc\RiftExplorer
32BitBuildByGabonnie\node_modules\electron\dist\resources\default_app.asar\main.
js:109:16)
    at Object.<anonymous> (G:\The ParadoxBoxTrox\Tools and Misc\RiftExplorer32Bi
tBuildByGabonnie\node_modules\electron\dist\resources\default_app.asar\main.js:1
55:9)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)

**Comment by RayZz-** [comment]
open this zip file and replace the `app.js` in your rift explorer folder with the one in this zip
[app.zip](https://github.com/Pupix/rift-explorer/files/3826980/app.zip)

**Comment by GGPeridot** [comment]
okay..

**Comment by GGPeridot** [comment]
it doesn't leave any error message, but it doesn't work.. it still stuck at the "Waiting for League to start.."
I am also in garena server hopes if theres a solution

**Comment by GGPeridot** [comment]
> open this zip file and replace the `app.js` in your rift explorer folder with the one in this zip
> [app.zip](https://github.com/Pupix/rift-explorer/files/3826980/app.zip)
hello?

**Comment by RayZz-** [comment]
in command prompt type in `WMIC PROCESS WHERE name="LeagueClient.exe" GET ExecutablePath` and screenshot the result and put it here.

**Comment by yusufcorlu** [comment]
@RayZz- Can you tell me how to open rift explorer on a 32 bit computer

**Comment by RayZz-** [comment]
Currently rift-explorer does not support 32 bit however it is possible to build it using the instructions in the `README.md` if the repository
